[provides]
name = "deno"
dynamic = true
default = "1.29.1"
source = "https://github.com/denoland/deno/archive/refs/tags/v{{version}}.tar.gz"

[provides.install]
cmd = """
cd deno-{{version}}
cargo build --release
mv target/release/deno {{binloc}}
"""
test = """
cat << EOF > test.ts
console.log("hello, world!")
EOF

if (deno run test.ts | grep '$1')
then
  exit 0
else
  exit 1
fi
"""